<?php
return array(
//*************************************附加设置***********************************
    'TMPL_ACTION_ERROR'      => THINK_PATH . 'Tpl/dispatch_jump.tpl', // 默认错误跳转对应的模板文件
    'TMPL_ACTION_SUCCESS'    => THINK_PATH . 'Tpl/dispatch_jump.tpl', // 默认成功跳转对应的模板文件
    'MODULE_ALLOW_LIST'      => array('Mobile'), //允许访问列表
    0      => array(),
    1      =>      array('Users','login'),//用户登录 post
    2      =>      array('Users','emailRegister'),//邮箱注册 post
    3      =>      array('Users','emailCodeLogin'),//邮箱验证码登录 post
    4      =>      array('Users','getEmailCode'),//获取邮箱验证码  get
    5      =>      array('UsersCenter','modifyPersonInfo'),//个人资料修改 post
    6      =>      array('UsersCenter','getPersonInfo'),//个人资料获取  get
    7      =>      array('UsersCenter','setNewPassword'),//设置新密码  post
    8      =>      array('UsersCenter','modifyPassWord'),//修改密码   post
    9      =>      array('UsersCenter','editAvatar'),//修改头像(头像上传)  post
    10      =>      array('UsersCenter','qrcodeLogin'),//app端扫码pc端登录 post
    11      =>      array('UsersCenter','emailRegister'),//
    12      =>      array('UsersCenter','emailRegister'),
    13      =>      array('UsersCenter','emailRegister'),
    14      =>      array('UsersCenter','emailRegister'),
    15      =>      array('UsersCenter','emailRegister'),
    16      =>      array('IndexCourse','homePageWaitingTaskNotice'),//首页待办任务消息数量
    17      =>      array('IndexCourse','homePageCourse'),//首页课程底部导航入口 get
    18      =>      array('Exam','myExam'),//我的考试 get
    19      =>      array('Exam','getQuest'),//参加考试 post
    20      =>      array('Survey','getList'),//我的调研-获取调研列表		post
    21      =>      array('Survey','getQues'),//我的调研-获取调研题目		post
    22      =>      array('Mine','appVersionUpdate'), //APP版本更新     GET
    23      =>      array('Users','getRegisteTissue'),//用户注册组织下拉选择
    24      =>      array('Users','emailRegister'),
    25      =>      array('Users','emailRegister'),
    26      =>      array('Users','emailRegister'),
    27      =>      array('Users','emailRegister'),
    28      =>      array('Users','emailRegister'),
    29      =>      array('Users','emailRegister'),
    30      =>      array('Users','emailRegister'),
    31      =>      array('Users','emailRegister'),
    32      =>      array('Users','emailRegister'),
    33      =>      array('Users','emailRegister'),
    34      =>      array('Users','emailRegister'),
    35      =>      array('Users','emailRegister'),
    36      =>      array('Users','emailRegister'),
    37      =>      array('Users','emailRegister'),
    38      =>      array('Users','emailRegister'),
    39      =>      array('Users','emailRegister'),
    40      =>      array('Users','emailRegister'),
    41      =>      array('Users','emailRegister'),
    42      =>      array('Users','emailRegister'),
    43      =>      array('Users','emailRegister'),
    44      =>      array('Users','emailRegister'),
    45      =>      array('Users','emailRegister'),
    46      =>      array('Users','emailRegister'),
    47      =>      array('Users','emailRegister'),
    48      =>      array('Users','emailRegister'),
    49      =>      array('Users','emailRegister'),
    50      =>      array('Users','emailRegister'),
    51      =>      array('Users','emailRegister'),
    52      =>      array('Users','emailRegister'),
    53      =>      array('Users','emailRegister'),
    54      =>      array('PublicCourse','emailRegister'),
    55      =>      array('PublicCourse','getSonTree'),//公开课课程分类二三级类获取 get
    56      =>      array('PublicCourse','getFatherTree'),//公开课课程分类一级类获取 get
    57      =>      array('PublicCourse','contentComment'),//课程评论/回复评论
    58      =>      array('PublicCourse','deleteComment'),//公开课评论删除评论
    59      =>      array('PublicCourse','praise'),//课程评论点赞/取消点赞
    60      =>      array('PublicCourse','note'),//公开课笔记 get
    61      =>      array('PublicCourse','getCommentList'),//公开课评论列表 get
    62      =>      array('PublicCourse','courseDetailsList'),//公开课目录 get
    63      =>      array('PublicCourse','courseDetails'),//公开课详情 get
    64      =>      array('PublicCourse','homePages'),//首页公开课程列表(更多)  get
    65      =>      array('Mine','addMyCourse'),//加入我的课程
    66      =>      array('PublicCourse','getFatherTree'),//获取课程分类一级类 get
    67      =>      array('PublicCourse','getSonTree'),//获取课程分类二三级类 get
    68      =>      array('PublicCourse','emailRegister'),
    69      =>      array('PublicCourse','emailRegister'),
    70      =>      array('PublicCourse','emailRegister'),
    71      =>      array('PublicCourse','emailRegister'),
    72      =>      array('Banner','getCarouselFigure'),//首页banner图     get
    73      =>      array('Integration','getExchangeIntergration'),//获取学分兑换积分所需显示的数据   get
    74      =>      array('Integration','IntergrationExchange'),//学分兑换积分   post
    75      =>      array('LineTrain','lineTrainList'),//线下培训班列表（选修） get
    76      =>      array('LineTrain','lineTrainDetail'),//线下培训班详情（选修） get
    77      =>      array('LineTrain','applyRegistration'),//立即报名     post
    78      =>      array('Integration','applyAddCredits'),//申请加学分 post
    79      =>      array('News','getNewsCommentList'),//获取资讯评论列表 get
    80      =>      array('News','createNewsComment'),//资讯评论 post
    81      =>      array('ActivityApply','activityList'),//活动报名列表  get
    82      =>      array('ActivityApply','activityDetails'),//活动详情  get
    83      =>      array('ActivityApply','activityRegistration'),//立即报名 post
    84      =>      array('BusinessTribe','getTopicList'),//业务部落里的话题列表(业务部落和我的部落)(有加入或者是自己创建的才能发布话题和发布评论回复)  get
    85      =>      array('BusinessTribe','getBusinessTribeList'),//获取业务部落列表 get
    86      =>      array('BusinessTribe','applyJoinTopicGroup'),//申请加入小组或部落 post
    87      =>      array('BusinessTribe','exitTopicGroup'),//退出话题小组 post
    88      =>      array('BusinessTribe','getOneTopicComment'),//业务部落里的一级话题评论 get
    89      =>      array('BusinessTribe','topicPraise'),//话题点赞，评论话题点赞 post
    90      =>      array('BusinessTribe','getTwoThreeTopicComment'),//业务部落里的二三级话题评论 get
    91      =>      array('BusinessTribe','topicComment'),//话题评论 post type=0一级评论，1二级评论
    92      =>      array('BusinessTribe','getPraiseCommentNotice'),//业务部落与我相关的点赞和评论通知 get
    93      =>      array('News','replyNewsComment'),//回复资讯评论 post
    94      =>      array('News','newsCommentPraise'),//资讯点赞，取消点赞  post
    95      =>      array('Users','emailRegister'),
    96      =>      array('Users','emailRegister'),
    97      =>      array('AuditTask','getAuditOneList'), //审核任务一级列表
    98      =>      array('AuditTask','getAuditTwoList'), //审核任务二级列表
    99      =>      array('AuditTask','auditTaskDetail'), //审核详情
    100      =>     array('AuditTask','operateAuditTask'),//审核操作
    101      =>      array('AuditTask','emailRegister'),
    102      =>      array('FriendsCircle','getPraiseCommentNotice'),//圈友动态与我相关的点赞和评论通知 get
    103      =>      array('Users','emailRegister'),
    104      =>      array('Users','emailRegister'),
    105      =>      array('Users','emailRegister'),
    106      =>      array('Users','emailRegister'),
    107      =>      array('Users','emailRegister'),
    108      =>      array('Users','emailRegister'),
    109      =>      array('Users','emailRegister'),
    110      =>      array('Users','emailRegister'),
    111      =>      array('Users','emailRegister'),
    112      =>      array('Users','emailRegister'),
    113      =>      array('Users','emailRegister'),
    114      =>      array('Users','emailRegister'),


);
